[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-weak-intrinsics"]

[target.thumbv4t-none-eabi]
runner = "mgba-qt"
rustflags = [
  "-Clinker=arm-none-eabi-ld",
  "-Clink-arg=-Tlinker_scripts/mono_boot.ld",
  "--emit=mir",
]
